{% set name = "dtool_http" %}
{% set reponame = "dtool-http" %}
{% set author = "jic-dtool" %}
{% set version = "0.2.1" %}
{% set sha256 = "ddbb6b3c01e37cd9588685edd31dbac978f2199e4c0e25cbeb90734b9b1a620c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ reponame }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - dtool_serve_directory = dtool_http.server:cli
    - dtool_publish_dataset = dtool_http.publish:cli
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - setuptools
    - dtoolcore
    - requests

test:
  imports:
    - dtool_http
    - dtool_http.server
    - dtool_http.publish
    - dtool_http.storagebroker
  commands:
    - dtool_serve_directory --help
    - dtool_publish_dataset --help

about:
  home: http://github.com/{{ author }}/{{ reponame }}
  license: MIT
  license_file: LICENSE.rst
  summary: 'HTTP support to dtool for read only access to datasets'

  dev_url: https://github.com/{{ author }}/{{ reponame }}

extra:
  recipe-maintainers:
    - pvanheus
