{% set name = "dtool_http" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-http/dtool-http-{{ version }}.tar.gz
  sha256: "02f581435369252d53e8c283cd5d3726404c0bf1858a1ddebdf15cd8e9a58b8e"

build:
  number: 2
  noarch: python
  entry_points:
    - dtool_serve_directory = dtool_http.server:cli
    - dtool_publish_dataset = dtool_http.publish:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - setuptools
    - dtoolcore >=3.17
    - requests

test:
  imports:
    - dtool_http
    - dtool_http.server
    - dtool_http.publish
    - dtool_http.storagebroker
  commands:
    - dtool_serve_directory --help
    - dtool_publish_dataset --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtool-http
  license: MIT
  license_file: LICENSE.rst
  summary: HTTP support to dtool for read only access to datasets
  doc_url: https://github.com/jic-dtool/dtool-http
  dev_url: https://github.com/jic-dtool/dtool-http

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
