travis:
  secure:
    BINSTAR_TOKEN: 2MxTqOUi2S27iCNGOexNgaYev/Bl3UJ/m+l4qPSI19PbW5ew43kdzhnjnc/+rQ1tH87AULgwa6uydTQQg3PPaL6joeS/BViErAMpuSxk7gWcHQgmmcdMrjSBYGBM9AzHuh2m+BVjwF3ABY++X0qiJyV5PS8p5RIMEA+xpHL98kVQkOQ/oXJQee+5V2BP+4BKSIbZn9Awytun9wBqtSrczs+jlaYVhr+HzqXWorlS293p+YGhyyHkDqqrCwQyuo3tEEat8vR3FboA8/CsM6zPVt+KLJpmnrlSvXlY1Lff5EBWw9Rx3uym/KqwV6YyRCUyOIvVLbYNSFWfPYgFpQNgV+nCTmogLKFgkn+UwFxpVeyWrVVl/4E4hn3czghP58YXQxQkDCjZvHxFacI53zW1gGsM5b6TCnUtq1s4WnwtVzqYtniWw5WXmIvezkt19CUkTLj6uBcOv6/M9g/HJV8gw6SS35s2ZuyMKWdmHscgCU+1Ie85pm57nSUriUNyql4KFpHjBjABQJ1+lGdCfoCrg1czOn6yBqKM+yv7JHTgY17Pv2gBRAPrSgKhFvPH1QoaWw97rm8FeOdUf8ieDs55JBJDUF5uUAc5YUI1UKDkFlxI71aah/Eyv+AcK2U1nyw4ihN9gW/VlhLazLfyNvKo6Gxu3Ewy7O8yUWbGRsyBi00=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
